version: '3'

services:
  web:
    image: jitsi/web:stable-8719
    restart: unless-stopped
    environment:
      - ENABLE_AUTH=0
      - ENABLE_GUESTS=1
      - PUBLIC_URL=https://meet.octa-bim.shop
    volumes:
      - ./web-config:/config
      - ./web-custom:/usr/share/jitsi-meet
      - ./interface_config:/interface_config
    labels:
      dokploy.expose: "true"
      dokploy.ssl: "true"
      dokploy.domain: "meet.octa-bim.shop"

  prosody:
    image: jitsi/prosody:stable-8719
    restart: unless-stopped
    volumes:
      - ./prosody-config:/config

  jicofo:
    image: jitsi/jicofo:stable-8719
    restart: unless-stopped
    volumes:
      - ./jicofo-config:/config

  jvb:
    image: jitsi/jvb:stable-8719
    restart: unless-stopped
    ports:
      - '10000:10000/udp'
    volumes:
      - ./jvb-config:/config
