version: '3'

services:
  web:
    image: jitsi/web:stable-8719
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./web/custom:/usr/share/jitsi-meet/custom
    environment:
      - ENABLE_LETSENCRYPT=1
      - LETSENCRYPT_DOMAIN=meet.octa-bim.shop
      - LETSENCRYPT_EMAIL=contact@octa-bim.shop
      - PUBLIC_URL=https://meet.octa-bim.shop