version: '3'

services:
  traefik:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.le.acme.httpchallenge=true"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.le.acme.email=contact@octa-bim.shop"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./letsencrypt:/letsencrypt"
    restart: unless-stopped

  web:
    image: jitsi/web:stable-8719
    restart: unless-stopped
    environment:
      - ENABLE_AUTH=0
      - ENABLE_GUESTS=1
      - PUBLIC_URL=https://meet.octa-bim.shop
    volumes:
      - ./web-config:/config
      - ./web-custom:/usr/share/jitsi-meet
      - ./interface_config:/interface_config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jitsi.rule=Host(`meet.octa-bim.shop`)"
      - "traefik.http.routers.jitsi.entrypoints=websecure"
      - "traefik.http.routers.jitsi.tls.certresolver=le"

  prosody:
    image: jitsi/prosody:stable-8719
    restart: unless-stopped
    volumes:
      - ./prosody-config:/config

  jicofo:
    image: jitsi/jicofo:stable-8719
    restart: unless-stopped
    volumes:
      - ./jicofo-config:/config

  jvb:
    image: jitsi/jvb:stable-8719
    restart: unless-stopped
    ports:
      - '10000:10000/udp'
    volumes:
      - ./jvb-config:/config
